import numpy as np
import torch
import random
from scipy.integrate import simpson


def set_seed(seed=42):
    """Set RNG seeds for reproducibility."""
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False


class BeamDisturbanceProjector:
    def __init__(self, L=5.0, D=0.05, thickness=0.002, rho=2800, n_modes=4):
        """
        Initialize beam model parameters.
        """
        self.L = L
        self.rho_A = rho * (np.pi * D * thickness)
        self.x_mesh = np.linspace(0, L, 500)
        self.n_modes = n_modes
        # Cantilever modal roots (beta * L)
        self.betas = np.array([1.875, 4.694, 7.855, 10.996])[:n_modes]

        # Precompute modal shapes and modal masses
        self.Mi = []
        self.phi_funcs = []

        for i in range(n_modes):
            beta = self.betas[i] / L
            sigma = (np.cosh(beta * L) + np.cos(beta * L)) / (np.sinh(beta * L) + np.sin(beta * L))
            phi_x = (np.cosh(beta * self.x_mesh) - np.cos(beta * self.x_mesh)) - \
                    sigma * (np.sinh(beta * self.x_mesh) - np.sin(beta * self.x_mesh))
            self.phi_funcs.append(phi_x)
            mi = simpson(self.rho_A * phi_x ** 2, x=self.x_mesh)
            self.Mi.append(mi)

    def project_jitter(self):
        coeffs = []
        for i in range(self.n_modes):
            spatial_integral = simpson(-self.rho_A * self.phi_funcs[i], x=self.x_mesh)
            coeffs.append(spatial_integral / self.Mi[i])
        return np.array(coeffs)

    def project_maneuver(self):
        coeffs = []
        for i in range(self.n_modes):
            spatial_integral = simpson(-self.rho_A * self.x_mesh * self.phi_funcs[i], x=self.x_mesh)
            coeffs.append(spatial_integral / self.Mi[i])
        return np.array(coeffs)

    def get_phi_at_x(self, x_loc):
        """Return modal shape values at x_loc (for Impact)."""
        idx = (np.abs(self.x_mesh - x_loc)).argmin()
        return np.array([self.phi_funcs[i][idx] for i in range(self.n_modes)])

    def get_static_coeffs(self):
        """
        Export static coefficients for multiprocessing.
        This avoids sending the full object across processes.
        """
        return {
            'jitter_coeffs': self.project_jitter(),
            'maneuver_coeffs': self.project_maneuver(),
            'Mi': np.array(self.Mi),
            'phi_funcs_data': self.phi_funcs,  # keep data if finer reconstruction is needed
            'x_mesh': self.x_mesh,
            # For Impact fast evaluation, keep minimal data so workers can compute phi(x).
        }


# --- Utility functions ---

def create_noise_data(tn, dt=0.01, option='normal', system_config=None, mt_data=None, projector_data=None):
    """
    Args:
        projector_data (dict): generated by BeamDisturbanceProjector.get_static_coeffs()
                               or an object that provides the required coefficients.
    """
    # Robust checks
    if not isinstance(tn, (int, np.integer)) or tn <= 0:
        raise ValueError("tn must be positive integer")

    valid_options = ['normal', 'jitter', 'maneuver', 'impact', 'mixed', 'thermal', 'free']
    if option not in valid_options:
        raise ValueError(f"Unknown option: {option}")

    time_axis = np.arange(tn) * dt
    modal_forces = np.zeros((tn, 4))

    # Read projector coefficients (dict from multiprocessing path)
    jitter_coeffs = projector_data['jitter_coeffs']
    maneuver_coeffs = projector_data['maneuver_coeffs']
    Mi_vals = projector_data['Mi']

    # ----------------------------------------------------
    # 1) Base noise
    # ----------------------------------------------------
    base_std = 0.001
    for i in range(4):
        modal_forces[:, i] += np.random.normal(0, base_std, tn)

    # ----------------------------------------------------
    # 2) Jitter: always present for non-normal modes
    # ----------------------------------------------------
    if option not in ['normal', 'free']:
        f_base = np.random.uniform(80, 200)
        amp = np.random.uniform(0.002, 0.008)
        jitter_signal = np.zeros(tn)
        harmonics = [1.0, 2.0, 3.5, 4.3]
        for h in harmonics:
            rand_phi = np.random.uniform(0, 2 * np.pi)
            inst_freq = 2 * np.pi * h * f_base * (1 + 0.005 * np.sin(2 * np.pi * 0.2 * time_axis))
            jitter_signal += (amp / h) * np.sin(inst_freq * time_axis + rand_phi)

        for i in range(4):
            modal_forces[:, i] += jitter_coeffs[i] * jitter_signal

    # ----------------------------------------------------
    # 3) Mode-specific components
    # ----------------------------------------------------

    # -> Maneuver (rest-to-rest)
    if option in ['maneuver', 'mixed']:
        t_start = np.random.uniform(0.1, 0.2) * tn * dt
        duration = np.random.uniform(1.5, 3.5)
        max_alpha = np.random.uniform(0.05, 0.15)

        # Random direction of the slew (keeps rest-to-rest property)
        direction = np.random.choice([-1.0, 1.0])

        mask = (time_axis >= t_start) & (time_axis < t_start + duration)
        if np.any(mask):
            t_local = time_axis[mask] - t_start

            alpha_t = np.zeros(tn)

            # Split into two halves: accelerate then decelerate (net rate change = 0)
            half = 0.5 * duration
            mask1 = mask & (time_axis < t_start + half)
            mask2 = mask & (time_axis >= t_start + half)

            if np.any(mask1):
                t1 = time_axis[mask1] - t_start
                alpha_t[mask1] = direction * max_alpha * 0.5 * (1 - np.cos(2 * np.pi * t1 / duration))

            if np.any(mask2):
                t2 = time_axis[mask2] - (t_start + half)
                alpha_t[mask2] = -direction * max_alpha * 0.5 * (1 - np.cos(2 * np.pi * t2 / duration))

            for i in range(4):
                modal_forces[:, i] += maneuver_coeffs[i] * alpha_t

    # -> Impact (force it to occur in the early part)
    if option == 'impact':
        t_imp_start = np.random.uniform(0.05, 0.10) * tn * dt
        x_loc = np.random.uniform(1.0, 4.8)
        f_peak = np.random.uniform(80, 200)  # stronger impact
        dt_imp = 0.1

        start_idx = int(t_imp_start / dt)
        steps_imp = int(dt_imp / dt)
        end_idx = min(start_idx + steps_imp, tn)

        if start_idx < tn:
            t_local = np.arange(end_idx - start_idx) * dt
            pulse = f_peak * np.sin(np.pi * t_local / dt_imp)

            # Lightweight phi(x) approximation without external objects
            # Requires L and betas; we keep them fixed to match projector defaults
            L = 5.0
            betas = np.array([1.875, 4.694, 7.855, 10.996])

            imp_coeffs = []
            for k in range(4):
                beta = betas[k] / L
                bx = beta * x_loc
                bL = betas[k]
                sigma = (np.cosh(bL) + np.cos(bL)) / (np.sinh(bL) + np.sin(bL))
                phi_val = (np.cosh(bx) - np.cos(bx)) - sigma * (np.sinh(bx) - np.sin(bx))
                imp_coeffs.append(phi_val / Mi_vals[k])

            for i in range(4):
                modal_forces[start_idx:end_idx, i] += imp_coeffs[i] * pulse

    # -> Thermal
    if option in ['thermal', 'mixed'] and mt_data is not None:
        if system_config is None:
            # If no config, ignore thermal contribution
            pass
        else:
            mt_vec = mt_data.flatten()
            if len(mt_vec) < tn:
                mt_vec = np.tile(mt_vec, int(np.ceil(tn / len(mt_vec))))
            mt_slice = mt_vec[:tn]

            for i in range(4):
                coeff = system_config.get(f'D{i + 1}', 0.0)
                modal_forces[:, i] += coeff * mt_slice

    # -> Free vibration (small deterministic impulse)
    if option == 'free':

        t_imp_start = 0.01     # fixed early excitation
        x_loc = 5.0            # beam tip
        f_peak = 3.0           # small force
        dt_imp = 0.08          # short duration

        start_idx = int(t_imp_start / dt)
        steps_imp = int(dt_imp / dt)
        end_idx = min(start_idx + steps_imp, tn)

        if start_idx < tn:

            t_local = np.arange(end_idx - start_idx) * dt
            pulse = f_peak * np.sin(np.pi * t_local / dt_imp)

            # same projection as impact
            L = 5.0
            betas = np.array([1.875, 4.694, 7.855, 10.996])

            imp_coeffs = []

            for k in range(4):
                beta = betas[k] / L
                bx = beta * x_loc
                bL = betas[k]

                sigma = (np.cosh(bL) + np.cos(bL)) / (np.sinh(bL) + np.sin(bL))

                phi_val = (np.cosh(bx) - np.cos(bx)) - sigma * (np.sinh(bx) - np.sin(bx))

                imp_coeffs.append(phi_val / Mi_vals[k])

            for i in range(4):
                modal_forces[start_idx:end_idx, i] += imp_coeffs[i] * pulse

    return {f'F{i + 1}': np.column_stack([time_axis, modal_forces[:, i]]) for i in range(4)}
